// server/src/models/Project.js
// Defines the Project model — blueprint for project data in MongoDB
// Every project a user creates becomes one document in the 'projects' collection

const mongoose = require('mongoose');

const projectSchema = new mongoose.Schema(
    {
        // Links the project to the user who created it
        // ObjectId is the data type for MongoDB document IDs
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: [true, 'User ID is required']
        },

        // The name the user gives their project
        projectName: {
            type: String,
            required: [true, 'Project name is required'],
            trim: true
        },

        // Optional GitHub URL if the user connects a repository
        repositoryUrl: {
            type: String,
            default: ''
        },

        // Plain English summary of the codebase
        // Generated by AI after analyzing the uploaded repository
        // Empty initially — filled after Phase 3 analysis
        repositorySummary: {
            type: String,
            default: ''
        },

        // Array of technologies detected in the uploaded codebase
        // Example: ['React', 'Node.js', 'Express', 'MongoDB']
        // Empty initially — filled after Phase 3 analysis
        detectedTechnologies: {
            type: [String],
            default: []
        },

        // Detected API routes stored as a JSON string
        // Example: '[{"method":"GET","path":"/api/users"}]'
        // Empty initially — filled after Phase 3 analysis
        detectedRoutes: {
            type: String,
            default: '[]'
        },

        // Folder structure of the uploaded repository
        // Stored as a newline-separated string of file paths
        // Empty initially — filled after Phase 3 analysis
        folderStructure: {
            type: String,
            default: ''
        },

        // Path to the uploaded ZIP file on the server
        // Used by the analysis service to find and read the file
        uploadedFilePath: {
            type: String,
            default: ''
        },

        // Tracks what stage the project is at
        // 'created'  — project just created, no repository uploaded yet
        // 'analyzed' — repository uploaded and analyzed successfully
        // 'ready'    — tests have been generated
        status: {
            type: String,
            enum: ['created', 'analyzed', 'ready'],
            default: 'created'
        }
    },

    {
        // Automatically adds createdAt and updatedAt fields
        timestamps: true
    }
);

// Index on userId makes fetching all projects for a user much faster
projectSchema.index({ userId: 1 });

// Create the model from the schema
const Project = mongoose.model('Project', projectSchema);

module.exports = Project;