// server/src/models/Project.js
// Defines the Project model — blueprint for project data in MongoDB
// Every project a user creates becomes one document in the 'projects' collection

const mongoose = require('mongoose');

// ============================================
// SCHEMA DEFINITION
// ============================================
const projectSchema = new mongoose.Schema(
    {
        // ---- USERID FIELD ----
        // This field links the project to the user who created it
        // mongoose.Schema.Types.ObjectId is the data type for MongoDB IDs
        // ref: 'User' tells Mongoose this ID refers to a document in the User collection
        // This is called a "reference" — like a foreign key in SQL databases
        // Example value: "6a3fddfa9d79542867a55efe"
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: [true, 'User ID is required']
            // required because every project must belong to someone
        },

        // ---- PROJECT NAME FIELD ----
        // The name the user gives their project
        // Example: "E-commerce Backend", "My Portfolio Site"
        projectName: {
            type: String,
            required: [true, 'Project name is required'],
            trim: true
        },

        // ---- REPOSITORY URL FIELD ----
        // Optional GitHub URL if the user connects a repository
        // Example: "https://github.com/username/my-project"
        // Not required because the user can also upload a ZIP file instead
        repositoryUrl: {
            type: String,
            default: ''
            // default: '' means if not provided, store an empty string
        },

        // ---- REPOSITORY SUMMARY FIELD ----
        // A plain English summary of the codebase
        // Generated by the AI after analyzing the uploaded repository
        // Example: "This is a React + Node.js e-commerce app with 12 API routes"
        // Empty initially — gets filled after repository analysis in Phase 3
        repositorySummary: {
            type: String,
            default: ''
        },

        // ---- DETECTED TECHNOLOGIES FIELD ----
        // An array of technologies detected in the uploaded codebase
        // Example: ["React", "Node.js", "Express", "MongoDB", "TypeScript"]
        // Empty initially — gets filled after repository analysis in Phase 3
        // [] means the default value is an empty array
        detectedTechnologies: {
            type: [String],
            default: []
            // [String] means this is an array where every item must be a String
        },

        // ---- STATUS FIELD ----
        // Tracks what stage the project is at
        // 'created'  — project just created, no repository uploaded yet
        // 'analyzed' — repository uploaded and analyzed successfully
        // 'ready'    — tests have been generated, project is fully ready
        status: {
            type: String,
            enum: ['created', 'analyzed', 'ready'],
            // enum means only these exact values are allowed
            // any other value will be rejected by Mongoose
            default: 'created'
        }
    },

    {
        // Automatically adds createdAt and updatedAt timestamps
        timestamps: true
    }
);

// ============================================
// INDEX
// ============================================
// An index makes database queries faster
// We frequently search for "all projects belonging to user X"
// Adding an index on userId makes that search much faster
// Think of it like an index in a book — helps find things quickly
projectSchema.index({ userId: 1 });
// 1 means ascending order


// ============================================
// CREATE AND EXPORT THE MODEL
// ============================================
// MongoDB will automatically create a 'projects' collection
const Project = mongoose.model('Project', projectSchema);

module.exports = Project;